<?php include('partials/header.php'); ?>

<div class="hero-canvas">
  <!-- <div class="hd hd1"><img src="assets/images/logo-sm1.png" alt="">
      </div>
      <div class="hd hd2"><img src="assets/images/logo-sm2.png" alt="">
      </div> -->
  <div class="hw drive-pos">
    <h1 class="hw-text drive-txt rv-up">DRIVE</h1>
  </div>
  <div class="hero-img-pos rv-in">
    <div class="hero-img-box">
      <img src="assets/images/header.png" alt="Drive Growth" class="hero-img">
    </div>
  </div>
  <div class="hw growth-pos">
    <h1 class="hw-text growth-txt rv-up" data-delay="100">GROWTH</h1>
  </div>
  <div class="hero-left-block rv-up" data-delay="200">
    <a href="#contact" class="signup-btn">Sign Up</a>
    <p class="hero-tagline">Empower Your Brand with<br>Cutting Edge<br>Digital Solutions</p>
  </div>
  <div class="hero-stats rv-up" data-delay="300">
    <div class="stat">
      <div class="stat-n counter" data-target="150">0+</div>
      <div class="stat-l">Satisfied Clients</div>
    </div>
    <div class="stat-div"></div>
    <div class="stat">
      <div class="stat-n">
        <div class="stat-n counter" data-target="12000">1.2M+</div>
        <img src="assets/images/arrowtop.png" alt="">
      </div>
      <div class="stat-l">Generated by Our Clients</div>
    </div>
    <div class="stat-div"></div>
    <div class="stat">
      <div class="stat-n counter" data-target="740">0+</div>
      <div class="stat-l">Completed Projects</div>
    </div>
  </div>
</div>
</section>


<!-- ========================================================
     S2 — CUSTOM MOBILE APP DEVELOPMENT
     bg:#f3f4ee | heading Montserrat Bold 66.7px #178d71
     Left: text | Right: 2 phones + shield + Figma badges
======================================================== -->
<section class="s-mobile" id="work">
  <!-- Our Published applications pill — absolute within section, Figma: x=43.6% y=76% -->
  <div class="s2-pub-pill"><img src="assets/images/our.svg" alt=""></div>
  <div class="container">
    <div class="row align-items-center g-0 g-lg-5">

      <!-- LEFT: text content -->
      <div class="col-lg-6 rv-left s2-left-col">
        <h2 class="s2-heading">Custom Mobile<br>App Development</h2>
        <p class="s2-body mt-4">Go beyond the browser. Stay connected to your audience 24/7 with sleek, intuitive
          mobile apps designed to turn casual users into an active, loyal community through seamless interactions and
          instant push notifications.</p>

        <!-- Actual Figma badge images -->


      </div>

      <!-- RIGHT: two phones + shield logo -->
      <div class="col-lg-6 rv-right">
        <div class="s2-phones-wrap">

          <!-- Left phone -->
          <div class="s2-phone s2-phone-left">
            <div class="s2-phone-frame">
              <img src="assets/images/mobilebg.svg" alt="" class="s2-phone-frame-img">
              <div class="s2-phone-screen">
                <video class="s2-screen-img" autoplay loop muted playsinline preload="auto" poster="assets/images/section2_video.png">
                  <source src="assets/images/v1.mov" type="video/mp4">
                </video>
              </div>
              <img src="assets/images/l1.svg" alt="" class="s2-phone-overlay">
            </div>
          </div>

          <!-- Shield logo between phones -->
          <!-- <div class="s2-shield-wrap">
              <img src="https://www.figma.com/api/mcp/asset/a36aeaf6-7c81-49e1-893c-e38611213f21" alt="Shield"
                class="s2-shield">
            </div> -->

          <!-- Right phone -->
          <div class="s2-phone s2-phone-right">
            <div class="s2-phone-frame">
              <img src="assets/images/mobilebg.svg" alt="" class="s2-phone-frame-img">
              <div class="s2-phone-screen">
                <video class="s2-screen-img" autoplay loop muted playsinline preload="auto" poster="assets/images/section2_video.png">
                  <source src="assets/images/v2.MP4" type="video/mp4">
                </video>
              </div>
              <img src="assets/images/knotty.svg" alt="" class="s2-phone-overlay">
            </div>
          </div>

        </div>

        <!-- Store badges -->
        <div class="s2-badges">
          <a href="#"><img src="assets/images/appstore.svg" alt="Appstore" class="s2-badge-img"> </a>
          <a href="#"><img src="assets/images/googleplay.svg" alt="Google Play" class="s2-badge-img"> </a>
        </div>
      </div>

    </div>
  </div>
  <!-- Mascot — absolute bottom-left of section -->
  <div class="s2-review-row">
    <img src="assets/images/mascot.svg" alt="mascot" class="s2-mascot">
    <span class="s2-review-text">Check-out our reviews! 👇</span>
  </div>
</section>


<!-- ========================================================
     S3 — BUILT FOR IMPACT / SAPFORCE  (bg:#fcfaff)
     Fan is large background in center (opacity 0.08)
     Layout: Left device | Laptop center | Right device
======================================================== -->
<section class="s-sapforce" id="about">

  <!-- Fan: left-extended bg (Figma: fan at x=491, laptop at x=603 → fan pokes 112px to the left of laptop) -->
  <div class="sap-fan-bg" aria-hidden="true">
    <div class="sap-fan-spin">
      <img src="assets/images/fan.png" alt="" class="sap-fan-img">
    </div>
  </div>

  <div class="container sap-content">
    <!-- Partner Logos -->
    <div class="partner-logos-row rv-up mb-5">
      <div class="partner-logo">
        <img src="assets/images/google.svg" alt="Google" class="logo-img">
      </div>
      <div class="partner-logo">
        <img src="assets/images/pilot.svg" alt="Trustpilot" class="logo-img">
      </div>
      <div class="partner-logo">
        <img src="assets/images/bbb.svg" alt="Accredited Business" class="logo-img">
      </div>
      <div class="partner-logo">
        <img src="assets/images/clutch.svg" alt="Clutch" class="logo-img">
      </div>
    </div>

    <!-- Heading (centered, above media) -->
    <div class="row justify-content-center">
      <div class="col-xl-7 col-lg-9 text-center rv-up">
        <h2 class="sap-heading">Built For Impact<span class="dot-g">.</span></h2>
        <h3 class="sap-sub">Engineered For Growth<span class="dot-g">.</span></h3>
        <p class="sap-desc mt-3">Keep your audience hooked with lightning-fast, high-performance websites designed to
          turn casual clicks into loyal fans and steady conversions.</p>
      </div>
    </div>

    <!-- 3-column media: device | laptop | device -->
    <div class="sap-media-row">
      <div class="sap-dev-left rv-left">
        <img src="assets/images/s1.svg" alt="Left device" class="sap-dev-img">
      </div>
      <div class="sap-laptop-col rv-up" data-delay="100">
        <div class="sap-laptop-frame">
          <img src="assets/images/computer.png" alt="SAPFORCE laptop" class="sap-laptop-img">
          <div class="sap-laptop-screen">
            <video class="sap-screen-vid" autoplay loop muted playsinline preload="auto">
              <source src="assets/images/sapforce.mp4" type="video/mp4">
            </video>
          </div>
        </div>
      </div>
      <div class="sap-dev-right rv-right">
        <img src="assets/images/s2.svg" alt="Right device" class="sap-dev-img">
      </div>
    </div>
  </div>

  <!-- Tech bar: full-width dark strip -->
  <div class="tech-bar-full rv-up" data-delay="200">
    <div class="container tech-bar-inner">
      <span class="tech-label-txt">Technology <span class="fw-normal">Stack</span></span>
      <div class="tech-bar-sep"></div>
      <div class="tech-logos-row">
        <div class="tech-logos-track">
          <img src="assets/images/shopify.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/php.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/react.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/laravel.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/nest.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/next.svg" alt="Tech Logo" class="tl">
          <!-- duplicate for seamless loop -->
          <img src="assets/images/shopify.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/php.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/react.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/laravel.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/nest.svg" alt="Tech Logo" class="tl">
          <img src="assets/images/next.svg" alt="Tech Logo" class="tl">
        </div>
      </div>
    </div>
  </div>
</section>


<!-- ========================================================
     S4 — WORK / LOGO SHOWCASE  (bg:#fffefe)
     Bento grid: 4 cols × 3 rows, exact Figma positions
     Col1: dk-green(top) + red(tall) | Col2: img(span2) | Col3: gray+mini | Col4: vid-top + large
======================================================== -->
<section class="s-logos" id="logos">
  <div class="container">
    <p class="sap-desc mt-3 mb-5 text-center rv-up vis">Elevate your brand’s first impression. We deliver versatile,
      high-impact 2D designs paired with <br> premium 3D animations, giving your business a sophisticated, cohesive
      presence across all media.</p>
    <div class="bento">

      <!-- g1: dark green + floating icon above -->
      <div class="bc-g1-wrap grid-g1">
        <div class="bc bc-dk">
          <img src="assets/images/logos.svg" alt="logos" class="bi" />
        </div>
        <div class="bc-float-icon">
          <div class="fan-container">
            <img src="assets/images/greencircle.png" alt="" class="circle-bg" />
            <img src="assets/images/smallfan.png" alt="" class="fan-spin" />
          </div>
        </div>
      </div>

      <!-- g2: tall center image (col2, rows 1–2) -->
      <div class="bc bc-center grid-g2">
        <img src="assets/images/vertekal.svg" alt="VERTEKAL" class="bi" />
      </div>

      <!-- g3: gray card (col3, row1) -->
      <div class="bc bc-gray grid-g3">
        <img src="assets/images/mundo.svg" alt="mundo" class="bi" />
      </div>

      <!-- g4: video top-right (col4, row1) -->
      <div class="bc bc-vid-top grid-g4">
        <video class="bi" autoplay loop muted playsinline preload="auto">
          <source src="assets/images/logo2.mp4" type="video/mp4">
        </video>
      </div>

      <!-- g5: solid red card (col1, rows 2–3) -->
      <div class="bc bc-red grid-g5">
        <img src="assets/images/red2.svg" alt="red2" class="" />
      </div>

      <!-- g6: two square mini cards side by side (col3, row2) -->
      <div class="bc-mini-pair1 grid-g6">
        <div class="bc-mini-half">
          <img src="assets/images/c1.png" alt="c1" />
        </div>
        <div class="bc-mini-half">
          <img src="assets/images/c3.png" alt="c3" />
        </div>
      </div>

      <!-- g7: large image (col4, rows 2–3) -->
      <div class="bc bc-large grid-g7">
        <img src="assets/images/red11.svg" alt="red11" class="bi" />
      </div>

      <!-- g8: wide video (col2+col3, row3) -->
      <div class="bc bc-wide-vid grid-g8">
        <video class="bi" autoplay loop muted playsinline preload="auto">
          <source src="assets/images/logo1.mp4" type="video/mp4">
        </video>
      </div>

      <!-- g9: bear + grid mini cards below g5 (col1, row4) -->
      <div class="bc-mini-pair grid-g9">
        <div class="bc-mini-half">
          <img src="assets/images/s1.png" alt="s1" />
        </div>
        <div class="bc-mini-half">
          <img src="assets/images/m2.png" alt="m2" />
        </div>
      </div>

    </div>
  </div>
</section>


<!-- ========================================================
     S5 — HOW WE GROW BUSINESSES
     Figma: bg=#178d71 gradient, side photos outside container
     Cards: solid #178d71 @ 93% opacity, Montserrat Bold 30.9px
======================================================== -->
<section class="s-grow" id="grow">

  <!-- Full-section green gradient background -->
  <div class="grow-bg" style="background-image:url('assets/images/greenbgg.svg')"></div>

  <!-- LEFT side: team photo (top) + decorative green hollow frame (behind, extends below) -->
  <div class="grow-side-photo grow-photo-l">
    <div class="grow-l-wrap">
      <!-- Green hollow frame — same 400×494 area, behind the photo -->
      <img src="assets/images/vector2.png" alt="" ">
        <!-- Team meeting photo — 287×287, top-center of the frame area -->
        <img src=" assets/images/mask1.png" alt="" class="grow-l-photo">
    </div>
  </div>

  <!-- RIGHT side: decorative green frame (top) + product photo (below, overlapping) -->
  <div class="grow-side-photo grow-photo-r">
    <div class="grow-r-wrap">
      <!-- Green hollow frame — top element, 384×214 -->
      <img src="assets/images/vector1.png" alt="" class="h-15">
      <!-- Product photo — 256×256, starts ~39% down, overlapping frame -->
      <img src="assets/images/mask2.png" alt="" class="grow-r-photo">
    </div>
  </div>

  <div class="container grow-inner">

    <!-- Heading + description: Figma y=146, centered -->
    <div class="row justify-content-center">
      <div class="col-xl-8 col-lg-8 text-center rv-up">
        <h2 class="grow-heading">How We Grow<br>Businesses.</h2>
        <p class="grow-desc mt-3">We believe that holding our work to the highest standard is the only way to keep our
          clients ahead of the competition. Our advanced digital approach ensures you get a seamless, fast website
          designed to scale your business effortlessly.</p>
      </div>
    </div>

    <!-- 3 Service cards: Figma y=546, bg=#178d71 @93%, radius=20px -->
    <div class="row g-4 mt-7 justify-content-center">
      <div class="col-lg-4 col-md-6 rv-up" data-delay="0">
        <div class="grow-svc-card">
          <h4 class="grow-svc-title">Branding Service</h4>
          <p class="grow-svc-desc">Align your look with your value to command higher prices and dominate your market.
          </p>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 rv-up" data-delay="150">
        <div class="grow-svc-card">
          <h4 class="grow-svc-title">SEO Service</h4>
          <p class="grow-svc-desc">Turn your website into a 24/7 lead machine by dominating search results.</p>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 rv-up" data-delay="300">
        <div class="grow-svc-card">
          <h4 class="grow-svc-title">Marketing service</h4>
          <p class="grow-svc-desc">Stop wasting budget on vanity metrics. We launch high-performance marketing
            campaigns that amplify your brand's unique voice and turn casual clicks into measurable revenue.</p>
        </div>
      </div>
    </div>

  </div>
</section>


<!-- ========================================================
     S6 — BETTER PACKAGES / PRICING  (bg:#fcfaff)
======================================================== -->
<section class="s-pricing s-pad" id="pricing">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-auto text-center rv-up">
        <h2 class="price-heading">Better Packages<span class="dot-g">.</span></h2>
        <h3 class="price-sub">Better Prices<span class="dot-g">.</span></h3>
        <img src="assets/images/price-card.svg" alt="" class="price-sep">
      </div>
    </div>

    <div class="price-toggle rv-up ">
      <div class="toggle-track">
        <button class="toggle-opt active" data-mt="basic">Basic</button>
        <button class="toggle-opt" data-mt="custom">Custom</button>
      </div>
    </div>

    <div class="price-panes-wrapper">
    <!-- BASIC -->
    <div class="price-pane active" id="mt-basic">
      <div class="price-subtabs mt-4">
        <button class="pst active" data-plan="1">App Development</button>
        <button class="pst" data-plan="2">SEO</button>
        <button class="pst" data-plan="3">Website</button>
        <button class="pst" data-plan="4">Logo design</button>
        <button class="pst" data-plan="5">Marketing Service</button>
      </div>
      <div class="row g-4 justify-content-center mt-4">
        <div class="col-xl-5 col-lg-6">
          <div class="pc-light">
            <div class="pc-top">
              <div>
                <div class="pc-name">Custom Core</div>
                <p class="pc-desc">Tailored solution built around your unique goals.</p>
              </div>
              <div class="pc-price"><span class="pc-curr">$</span><span class="pc-val" id="b-v1">100</span></div>
            </div>
            <div class="pc-line"></div>
            <ul class="pc-list">
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> Full brand identity system</li>
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> Custom app development</li>
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> Dedicated account manager</li>
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> Enterprise SEO strategy</li>
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> 24/7 priority support</li>
            </ul>
          </div>
        </div>
        <div class="col-xl-5 col-lg-6">
          <div class="pc-dark">
            <img src="assets/images/Doscount.svg" alt="Most Popular" class="most-pop">
            <div class="pc-top">
              <div>
                <div class="pc-name pc-name-lt">Enterprise</div>
                <p class="pc-desc pc-desc-lt">Complete digital transformation for large scale enterprises.</p>
              </div>
              <div class="pc-price pc-price-lt"><span class="pc-curr">$</span><span class="pc-val" id="b-v2">200</span>
              </div>
            </div>
            <div class="pc-line pc-line-lt"></div>
            <ul class="pc-list pc-list-lt">
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> Multi-platform applications</li>
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> AI-powered integration</li>
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> Custom analytics dashboard</li>
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> Dedicated support team</li>
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> 6-month priority support</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- CUSTOM -->
    <div class="price-pane" id="mt-custom">
      <div class="price-subtabs mt-4">
        <button class="pst active" data-plan="1">App Development</button>
        <button class="pst" data-plan="2">SEO</button>
        <button class="pst" data-plan="3">Website</button>
        <button class="pst" data-plan="4">Logo design</button>
        <button class="pst" data-plan="5">Marketing Service</button>
      </div>
      <div class="row g-4 justify-content-center mt-4">
        <div class="col-xl-5 col-lg-6 rv-left">
          <div class="pc-light">
            <div class="pc-top">
              <div>
                <div class="pc-name">Custom Core</div>
                <p class="pc-desc">Tailored solution built around your unique goals.</p>
              </div>
              <div class="pc-price"><span class="pc-curr">$</span><span class="pc-val" id="c-v1">100</span></div>
            </div>
            <div class="pc-line"></div>
            <ul class="pc-list">
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> Full brand identity system</li>
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> Custom app development</li>
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> Dedicated account manager</li>
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> Enterprise SEO strategy</li>
              <li><img src="assets/images/tick1.svg" class="pc-chk" alt="✓"> 24/7 priority support</li>
            </ul>
          </div>
        </div>
        <div class="col-xl-5 col-lg-6 rv-right">
          <div class="pc-dark">
            <div class="pc-top">
              <div>
                <div class="pc-name pc-name-lt">Enterprise</div>
                <p class="pc-desc pc-desc-lt">Complete digital transformation for large scale enterprises.</p>
              </div>
              <div class="pc-price pc-price-lt"><span class="pc-curr">$</span><span class="pc-val" id="c-v2">200</span>
              </div>
            </div>
            <div class="pc-line pc-line-lt"></div>
            <ul class="pc-list pc-list-lt">
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> Multi-platform applications</li>
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> AI-powered integration</li>
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> Custom analytics dashboard</li>
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> Dedicated support team</li>
              <li><img src="assets/images/tick2.svg" class="pc-chk" alt="✓"> 6-month priority support</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</section>


<!-- ========================================================
     S7 — FEATURES / WHY US  (bg:#166855, 4 columns)
======================================================== -->
<section class="s-features">
  <div class="container">
    <div class="row g-0 features-row">
      <div class="col-lg-3 col-md-6 rv-up" data-delay="0">
        <div class="feat-col">
          <div class="feat-icon-wrap">
            <img src="assets/images/1f.svg" alt="Unique Designs" class="feat-icon">
          </div>
          <h4 class="feat-title">Unique Designs</h4>
          <p class="feat-desc">Professional design companies handle custom designs best. How about a free trial to get
            things started?</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 rv-up" data-delay="100">
        <div class="feat-col">
          <div class="feat-icon-wrap">
            <img src="assets/images/2f.svg" alt="Money Back Guarantee" class="feat-icon">
          </div>
          <h4 class="feat-title">Money Back Guarantee</h4>
          <p class="feat-desc">If you're unhappy with what you've received or we've failed to meet your deadline, you
            can request a refund.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 rv-up" data-delay="200">
        <div class="feat-col">
          <div class="feat-icon-wrap">
            <img src="assets/images/3f.svg" alt="Customer Satisfaction" class="feat-icon">
          </div>
          <h4 class="feat-title">Customer Satisfaction</h4>
          <p class="feat-desc">A business's success depends upon the happiness levels its customers share. Allow us to
            meet your expectations.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 rv-up" data-delay="300">
        <div class="feat-col feat-col-last">
          <div class="feat-icon-wrap">
            <img src="assets/images/4f.svg" alt="24/7 Support" class="feat-icon">
          </div>
          <h4 class="feat-title">24/7 Support</h4>
          <p class="feat-desc">Whether it's a new project or edits on your previous project, we cater to your needs in
            real-time.</p>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- ========================================================
     S8 — TEAM AT DEVPICKLES
     Figma: 1920×726px, bg=#fcfaff, left text + right photo
======================================================== -->
<section class="s-team" id="team">
  <div class="container team-wrap">
    <div class="row g-0 align-items-center">

      <!-- LEFT: WHY US? + heading + body + button + partner logos -->
      <div class="col-xl-7 col-lg-6 team-col-l rv-left">
        <p class="team-tag">WHY US?</p>
        <h2 class="team-heading rv-up">Team At Devpickles</h2>
        <p class="team-body rv-up" data-delay="100">We're trusted by the world's leading startups and enterprises
          featured in the Fortune 500 for building stronger relationships, optimizing their branding strategy, and
          changing how they do business. From custom website builders and user-friendly mobile app solutions to
          innovative logo designs, we offer everything you need to thrive in today's competitive landscape.</p>
        <p class="team-body rv-up" data-delay="150">We're trusted by the world's leading startups and enterprises
          featured in the Fortune 500 for building stronger relationships, optimizing their branding strategy, and
          changing how they do business. From custom website builders and user-friendly mobile app solutions to
          innovative logo designs, we offer everything you need to thrive in today's competitive landscape.</p>
        <a href="#contact" class="team-cta rv-up" data-delay="200">Learn More</a>
        <div class="team-logos rv-up" data-delay="250">
          <img src="assets/images/ibm.svg" alt="IBM" class="t-logo">
          <img src="assets/images/claude.svg" alt="Claude" class="t-logo">
          <img src="assets/images/google2.svg" alt="Google" class="t-logo">
          <img src="assets/images/notion.svg" alt="Notion" class="t-logo">
          <img src="assets/images/adobe.svg" alt="Adobe" class="t-logo">
        </div>
      </div>

      <!-- RIGHT: conference room photo -->
      <div class="col-xl-5 col-lg-6 team-col-r rv-right">
        <div class="team-photo-wrap">
          <img src="assets/images/team.png" alt="Team at DevPickles" class="team-photo">
        </div>
      </div>

    </div>
  </div>
</section>


<!-- ========================================================
     FOOTER — CTA top (Eden #166855) + Links (Zuccini #043c2f)
======================================================== -->
<?php include('partials/footer.php'); ?>